name: ecommerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  auto_animated: ^3.0.1
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1 
  device_preview: ^1.1.0
  dropdown_search: ^3.0.1
  equatable: ^2.0.5
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_local_notifications: ^9.5.3+1
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_ringtone_player: ^3.2.0
  flutter_svg: ^0.23.0+1
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.4
  geolocator: ^8.0.5
  get: ^4.6.1
  google_fonts: ^4.0.4 
  google_maps_flutter: ^2.2.8
  google_sign_in: ^5.3.1
  grouped_list: ^4.2.0
  http: ^0.13.4
  image_picker: ^0.7.2+1
  image_pickers: ^2.0.0+2
  
  intl: ^0.18.0
  jiffy: ^5.0.0
  lottie: ^2.3.2
  path: ^1.8.0
  pin_code_fields: ^7.4.0
  qr_flutter: ^4.0.0
  responsive_builder: ^0.4.2
  scan: ^1.6.0
  shared_preferences: ^2.1.0
  show_up_animation: ^2.0.0
  sqflite: ^2.0.2
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/rive/

  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
